#!/bin/bash
# ppsfind -- find pps device by name
#
# Copyright (C) 2005-2007   Rodolfo Giometti <giometti@linux.it>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

SYS="/sys/class/pps/"

if [ $# -lt 1 ] ; then
	echo "usage: ppsfind <name>" >&2
	exit 1
fi

for d in $(ls $SYS) ; do
	if grep $1 $SYS/$d/name >& /dev/null || \
	   grep $1 $SYS/$d/path >& /dev/null ; then
		echo "$d: name=$(cat $SYS/$d/name) path=$(cat $SYS/$d/path)"
	fi
done

exit 0
